CREATE TABLE IF NOT EXISTS Account (
    id SERIAL PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    display_name TEXT,
    admin BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS Tag (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Thread (
    id SERIAL PRIMARY KEY,
    author_id INTEGER REFERENCES Account(id),
    title TEXT NOT NULL,
    created TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS Response (
    id SERIAL PRIMARY KEY,
    author_id INTEGER REFERENCES Account(id) ON DELETE CASCADE,
    thread_id INTEGER REFERENCES Thread(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS ThreadTag (
    tag_id INTEGER REFERENCES Tag(id) ON DELETE CASCADE,
    thread_id INTEGER REFERENCES Thread(id) ON DELETE CASCADE,
    UNIQUE(tag_id, thread_id)
);
