DROP TABLE IF EXISTS Account CASCADE;
DROP TABLE IF EXISTS Profile CASCADE;
DROP TABLE IF EXISTS Tag CASCADE;
DROP TABLE IF EXISTS Thread CASCADE;
DROP TABLE IF EXISTS Response CASCADE;
DROP TABLE IF EXISTS ThreadTag CASCADE;
